# Generated by Django 4.2.8 on 2024-01-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='CO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
