# Generated by Django 4.1.3 on 2024-01-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_tests',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='contact_hours',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='final_exam',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='rationale',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_lectures',
            field=models.CharField(max_length=255),
        ),
    ]
