# Generated by Django 4.1.3 on 2024-01-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_course_class_tests_alter_course_contact_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_tests',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='contact_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='final_exam',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='rationale',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_lectures',
            field=models.IntegerField(),
        ),
    ]
