# Generated by Django 4.1.3 on 2024-01-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_course_class_tests_alter_course_contact_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rem_fest', models.IntegerField()),
                ('rem_assign', models.IntegerField()),
                ('rem_exper', models.IntegerField()),
                ('rem_final', models.IntegerField()),
                ('un_fest', models.IntegerField()),
                ('un_assign', models.IntegerField()),
                ('un_exper', models.IntegerField()),
                ('un_final', models.IntegerField()),
                ('apply_fest', models.IntegerField()),
                ('apply_assign', models.IntegerField()),
                ('analyze_fest', models.IntegerField()),
                ('analyze_assign', models.IntegerField()),
                ('apply_exper', models.IntegerField()),
                ('apply_final', models.IntegerField()),
                ('eva_fest', models.IntegerField()),
                ('eva_assign', models.IntegerField()),
                ('eva_exper', models.IntegerField()),
                ('eva_final', models.IntegerField()),
                ('c_fest', models.IntegerField()),
                ('c_assign', models.IntegerField()),
                ('c_exper', models.IntegerField()),
                ('c_final', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(max_length=255),
        ),
    ]
