# Generated by Django 4.1.3 on 2024-01-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_assessment_alter_course_prerequisites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
