# Generated by Django 4.2.8 on 2024-03-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('faceToface', models.IntegerField()),
                ('nonfaceToface', models.IntegerField()),
                ('lecture', models.IntegerField()),
                ('exercise', models.IntegerField()),
                ('practical', models.IntegerField()),
                ('others', models.IntegerField()),
                ('ilearn', models.IntegerField()),
                ('totalSlt', models.IntegerField()),
            ],
        ),
    ]
