# Generated by Django 4.2.8 on 2024-03-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_outline_clos'),
    ]

    operations = [
        migrations.AddField(
            model_name='outline',
            name='att',
            field=models.ManyToManyField(default=[], to='api.attitude'),
        ),
        migrations.AddField(
            model_name='outline',
            name='knowledge',
            field=models.ManyToManyField(default=[], to='api.knowledge'),
        ),
        migrations.AddField(
            model_name='outline',
            name='skill',
            field=models.ManyToManyField(default=[], to='api.skill'),
        ),
    ]
