# Generated by Django 4.2.8 on 2024-03-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_outline_att_outline_knowledge_outline_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outline',
            name='clos',
            field=models.ManyToManyField(to='api.clo'),
        ),
    ]
