# Generated by Django 4.2.8 on 2024-04-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_outline_clos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outline',
            name='att',
        ),
        migrations.RemoveField(
            model_name='outline',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='outline',
            name='skill',
        ),
        migrations.AlterField(
            model_name='outline',
            name='clos',
            field=models.ManyToManyField(default=[], to='api.clo'),
        ),
    ]
