# Generated by Django 4.2.8 on 2024-04-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_outline_att_remove_outline_knowledge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outline',
            name='att',
            field=models.ManyToManyField(default=[], to='api.attitude'),
        ),
        migrations.AddField(
            model_name='outline',
            name='know',
            field=models.ManyToManyField(default=[], to='api.knowledge'),
        ),
        migrations.AddField(
            model_name='outline',
            name='skill',
            field=models.ManyToManyField(default=[], to='api.skill'),
        ),
    ]
