# Generated by Django 4.2.8 on 2024-04-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_outline_att_outline_know_outline_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outline',
            old_name='know',
            new_name='knows',
        ),
    ]
