# Generated by Django 4.2.8 on 2024-04-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_know_outline_knows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outline',
            old_name='att',
            new_name='atts',
        ),
        migrations.RenameField(
            model_name='outline',
            old_name='skill',
            new_name='skills',
        ),
    ]
