# Generated by Django 4.2.8 on 2024-04-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_att_outline_atts_rename_skill_outline_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outline',
            name='faceToface',
        ),
    ]
